from liaodd/ubuntu_with_163_mirror
run apt-get update
run apt-get install nginx -y
run apt-get install php5 php5-fpm php5-cli php5-mysql -y
add index.php /app/web/default/index.php
add default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
run rm /etc/nginx/sites-enabled/default